spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ENC(rv2x9lGbQu+aVdGYwq05LonjbchLGouh)
    url: ENC(oAF/Cuc3xMcECKrzrgDOQFi0I1CviXHmLUXYzO4lSF9oW2bWvHLsMjdGUwA/O8H2Xw9acuRQXWqfNFV4SPqavEMzjSJhIrBSREtLkUFwRv9C0+6CvtH9Uxp46cZ13UeKzYD9g2WlQMuYaF/NtuPgZ3zb2O9Eq2uIUkAnNJE7Tp1uSvbboMHyD3UvR6xRHayhCykAyB6fI3DquxWhji3jLSvld4Eot110tJR20zk+U+78rQDvIk1GyQ==)
    username: admin

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(nByHugM5cVyzCoGWtB7fivRjl/DHS2nNlatDZtY/b5E=)
    password: ENC(Ab/pF8aVcf/pUOJXUvSQS1gQV8EixUsT7Wg+IEBZ2UA=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

  mustache:
    suffix: .html

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

KEY:
  JWT: ENC(L+Da2qqjOez9Vi6plXZg5YqXmLHTcj+g)
  AES128 : ENC(LCF5IYuQ0W4SkwNM1nfCyDmMRg1S+vyu2srLWZ3uTqg=)

cloud:
  aws:
    credentials:
      accessKey: ENC(3Z+OyRTPBuFTVmqz+9KeT/jOjsgcGCdH9J+w1JmR12k=)
      secretKey: ENC(cwKingEYIkfICpt6YiuDjDGWfmuyC8vGP29ZOsa4cD2WzwFYVfo5xXWxWjvAykgGMTn+wTNzE4g=)
    s3:
      bucket: fork-fork-cake
    region:
      static: ap-northeast-2
    stack:
      auto: false


viewname:
  room: chat/room
  chat:
    rooms: chat/rooms
---

spring:
  config:
    activate:
      on-profile: "prod"

server.ssl.key-store: keystore.p12
server.ssl.key-store-password: ENC(0bK1+y9RglKiVtVsGYjTnKWrnWqSr/Ke)
server.ssl.keyStoreType: PKCS12
